fix(README.md): bump python runtime version to 3.10
Addresses error below, due to Type hinting syntax only available in Python >=3.10
```
def get_reference_list(list_name: str) -> List[str] | None:
TypeError: unsupported operand type(s) for |: '_GenericAlias' and 'NoneType'. [...]
```